# Deploys a Node.js app to an Azure Web App on Linux
name: Build and deploy Node.js app to Azure Web App - scribe-server-dev

on:
  push:
    branches:
      - azure/deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'

      - name: Install all dependencies (for build and typecheck using npm)
        run: npm install --legacy-peer-deps

      - name: Type check
        run: npm run typecheck

      - name: Build application
        run: npm run build

      - name: Check entrypoint works locally (optional, for quick validation)
        run: |
          node dist/src/index.js &
          sleep 5 # Give the app a moment to start
          kill %1 || true # Kill the background process, '|| true' prevents failure if process already exited

      - name: Create deployment package directory
        run: mkdir -p deployment

      - name: Copy production files to deployment package
        run: |
          cp -r dist deployment/
          cp package.json deployment/
          # If you want deterministic builds on Azure, you should commit package-lock.json
          # and copy it here. If not, npm will generate it on the fly in the next step.
          cp package-lock.json deployment/ || true # Copy if exists, don't fail if not

      - name: Install production-only dependencies in deployment package (using npm)
        run: |
          cd deployment
          npm install --prod --legacy-peer-deps # --legacy-peer-deps can help avoid issues with peer dependency warnings/errors

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deployment/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: deployment/

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'scribe-server-dev'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_947D34B0D69C4986A7E211253893C796 }}
          package: deployment/
          clean: true

      - name: Verify deployment (with retry logic)
        run: |
          echo "Waiting for app to start..."
          for i in $(seq 1 10); do
            response=$(curl -s -o /dev/null -w "%{http_code}" https://scribe-server-dev.azurewebsites.net)
            if [ "$response" -ge 200 ] && [ "$response" -lt 400 ]; then
              echo "App is up and running (HTTP $response)."
              exit 0
            else
              echo "App not ready yet (HTTP $response). Retrying in 10 seconds..."
              sleep 10
            fi
          done
          echo "App did not become ready within the timeout."
          exit 1
