name: Scribe Server CI/CD

on:
  push:
    branches:
      - main
      - azure/deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm run build

      - name: Prepare Deploy Folder
        run: |
          mkdir deploy
          cp -r dist package.json deploy/
          [ -f .npmrc ] && cp .npmrc deploy/
          cd deploy
          # Use npm for deployment to avoid dependency resolution issues
          npm install --production

      - name: Add Start Script
        run: |
          cd deploy
          node -e "
            const fs = require('fs');
            const pkg = require('./package.json');
            pkg.scripts = pkg.scripts || {};
            pkg.scripts.start = 'node dist/src/index.js';
            fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          "

      - name: Show Deploy Folder Contents (Debug)
        run: ls -R deploy

      - name: Zip Deploy Folder
        run: |
          cd deploy
          zip -r ../deploy.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'scribe-server-dev'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AAFEB4AF5C6640678CF82A95C3F936A7 }}
          package: deploy.zip

      - name: Test Deployment
        run: |
          echo "Waiting for deployment to complete..."
          sleep 60

          echo "=== Testing Root URL ==="
          curl -v -s -w "\nHTTP Status: %{http_code}\nResponse Time: %{time_total}s\n" \
            https://scribe-server-dev-f3c7f3a6f2bde7ec.westeurope-01.azurewebsites.net || echo "Connection test completed"

          echo "=== Testing /health Endpoint ==="
          curl -v -s -w "\nHTTP Status: %{http_code}\nResponse Time: %{time_total}s\n" \
            https://scribe-server-dev-f3c7f3a6f2bde7ec.westeurope-01.azurewebsites.net/health || echo "Health check completed"

      - name: Deployment Status
        if: always()
        run: |
          echo "=== Deployment Summary ==="
          echo "App Name: scribe-server-dev"
          echo "URL: https://scribe-server-dev-f3c7f3a6f2bde7ec.westeurope-01.azurewebsites.net"
          echo "Check Azure Portal for detailed logs: https://portal.azure.com/"