# Deploys a Node.js app to an Azure Web App on Linux
name: Build and deploy Node.js app to Azure Web App - scribe-server-dev

on:
  push:
    branches:
      - main
      - azure/deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the app (tsc + tsc-alias)
        run: pnpm run build

      - name: Run tests (optional)
        run: pnpm run test || echo "No tests found or tests failed"

      - name: Prune dev dependencies
        run: pnpm prune --prod

      - name: Clean up dev-only files
        run: |
          rm -rf .git .github tests __tests__ coverage .nyc_output
          rm -f .gitignore .eslintrc* .prettierrc* jest.config.* *.test.js *.spec.js

      - name: Create deployment package
        run: |
          zip -r release.zip . -x "*.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip release
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'scribe-server-dev'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_947D34B0D69C4986A7E211253893C796 }}
          package: .
          clean: true
