# Deploys a Node.js app to an Azure Web App on Linux
name: Build and deploy Node.js app to Azure Web App - scribe-server-dev

on:
  push:
    branches:
      - azure/deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload entire repository as artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'scribe-server-dev'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_947D34B0D69C4986A7E211253893C796 }}
          package: .
          clean: true

      - name: Verify deployment (with retry logic)
        run: |
          echo "Waiting for app to start..."
          for i in $(seq 1 10); do
            response=$(curl -s -o /dev/null -w "%{http_code}" https://scribe-server-dev.azurewebsites.net)
            if [ "$response" -ge 200 ] && [ "$response" -lt 400 ]; then
              echo "App is up and running (HTTP $response)."
              exit 0
            else
              echo "App not ready yet (HTTP $response). Retrying in 10 seconds..."
              sleep 10
            fi
          done
          echo "App did not become ready within the timeout."
          exit 1
