name: Scribe Server CI/CD 

on:
  push:
    branches:
      - main
      - azure/deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm run build

      - name: Prepare Deploy Folder
        run: |
          mkdir deploy
          cp -r dist package.json pnpm-lock.yaml deploy/
          [ -f .npmrc ] && cp .npmrc deploy/
          cd deploy
          pnpm install --prod --frozen-lockfile

      - name: Add Start Script (if needed)
        run: |
          cd deploy
          node -e "const fs = require('fs'); const pkg = require('./package.json'); if (!pkg.scripts) pkg.scripts = {}; pkg.scripts.start = pkg.scripts.start || 'node dist/server.js'; fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'scribe-server-dev'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AAFEB4AF5C6640678CF82A95C3F936A7 }}
          package: deploy

      - name: Test Deployment
        run: |
          echo "Waiting for deployment to complete..."
          sleep 60
          
          echo "=== Testing Deployment ==="
          curl -v -s -w "\nHTTP Status: %{http_code}\nResponse Time: %{time_total}s\n" \
            https://scribe-server-dev.azurewebsites.net/ || echo "Connection test completed"

          echo "Testing health endpoint..."
          curl -v -s -w "\nHTTP Status: %{http_code}\nResponse Time: %{time_total}s\n" \
            https://scribe-server-dev.azurewebsites.net/health || echo "Health check completed"

      - name: Deployment Status
        if: always()
        run: |
          echo "=== Deployment Summary ==="
          echo "App Name: scribe-server-dev"
          echo "URL: https://scribe-server-dev.azurewebsites.net/"
          echo "Check Azure Portal for detailed logs: https://portal.azure.com/"
