#
# Deploys a Node.js app to an Azure Web App on Linux
#

name: Build and deploy Node.js app to Azure Web App - scribe-server-dev

on:
  push:
    branches:
      - azure/deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm typecheck

      - name: Build application
        run: pnpm build

      - name: Check entrypoint works
        run: node dist/src/index.js &

      - name: Install production-only dependencies
        run: |
          rm -rf node_modules
          pnpm install --frozen-lockfile --prod

      - name: Create deployment package directory
        run: mkdir -p deployment

      - name: Copy production files to deployment package
        run: |
          cp -r dist deployment/
          cp -r node_modules deployment/
          cp package.json deployment/
          cp pnpm-lock.yaml deployment/

      - name: Create zip archive
        run: |
          cd deployment
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'scribe-server-dev'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_947D34B0D69C4986A7E211253893C796 }}
          package: release.zip
          clean: true
