# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - scribe-server-dev

on:
  push:
    branches:
      - azure/deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm typecheck

      - name: Build application
        run: pnpm build

      - name: Install production dependencies
        run: |
          # Clean install production dependencies
          rm -rf node_modules
          pnpm install --frozen-lockfile --prod

      - name: Create deployment package
        run: |
          # Create deployment directory with built files
          mkdir deployment-package
          cp -r dist deployment-package/
          cp -r node_modules deployment-package/
          cp package.json deployment-package/
          cp pnpm-lock.yaml deployment-package/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deployment-package/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Clean and prepare deployment
        run: |
          # Create cleanup script
          cat > cleanup.ps1 << 'EOF'
          # PowerShell script to clean wwwroot
          $webappPath = $env:WEBSITE_SITE_PATH
          if ($webappPath) {
            Get-ChildItem -Path $webappPath -Recurse | Remove-Item -Force -Recurse
            Write-Host "Cleaned wwwroot directory"
          }
          EOF

          # Create deployment script
          cat > deploy.cmd << 'EOF'
          @echo off
          echo Cleaning deployment directory...

          REM Clean everything except the new deployment files
          for /f "delims=" %%i in ('dir /b /a-d') do (
            if not "%%i"=="dist" if not "%%i"=="node_modules" if not "%%i"=="package.json" if not "%%i"=="deploy.cmd" (
              del "%%i" 2>nul
            )
          )

          REM Clean directories except our deployment dirs
          for /f "delims=" %%i in ('dir /b /ad') do (
            if not "%%i"=="dist" if not "%%i"=="node_modules" (
              rmdir /s /q "%%i" 2>nul
            )
          )

          echo Deployment directory cleaned
          EOF

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'scribe-server-dev'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_947D34B0D69C4986A7E211253893C796 }}
