# Validates Pull Requests by running linting, testing, and type checking
name: Pre-merge
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.0
          cache: npm

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Lint and format check
        run: |
          npm run lint
          npm run format:check

      - name: Type check
        run: npm run typecheck

      - name: Run tests
        run: npm run test

      - name: Build test
        run: npm run build
